- name: demo on filters/functions
  hosts: local
  connection: local
  vars:
    topics: linux, shell, ansible, terraform
    case_convert: devops with aws
    myIp: "54.235.37.389"
    tagsMap:
      name: ansible
      project: roboshop
      component: catalogue
    tagsList: [
      {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "catalogue"
        }
    ]

  tasks:
  - name: greeting
    ansible.builtin.debug:
      msg: "Hi Bhavitha, {{ GREETING | default('Good Morning!') }}"

  - name: convert string to list
    ansible.builtin.debug:
      msg: "{{ topics | split(',') }}"

  - name: convert map to list
    ansible.builtin.debug:
      msg: "{{ tagsMap | dict2items }}"

  - name: convert list to map
    ansible.builtin.debug:
      msg: "{{ tagsList | items2dict }}"

  - name: read students yaml
    ansible.builtin.set_fact:        #setting the variable
      student_yaml: "{{ lookup('file', 'students.yaml' ) | from_yaml }}"

  - name: convert YAML to JSON
    ansible.builtin.debug:
      msg: "{{ student_yaml | to_nice_json }}"

  - name: convert lower to upper case_convert
    ansible.builtin.debug:
      msg: "{{ case_convert | upper }}"

  - name: convert upper to lower case_convert
    ansible.builtin.debug:
      msg: "{{ case_convert | lower }}"

  - name: check ipv4
    ansible.builtin.debug:
      msg: "{{ myIp | ansible.utils.ipv4 }}"        #belongs to the ansible.utils collection, and it requires a Python library called: netaddr