- name: install packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install package
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:                                             #loop's data type is list(-), data type of each entry is map/dictionary
    - { name: "mysql", state: "present" }
    - { name: "nginx", state: "absent" }